services:
  go:
    container_name: go-chi
    volumes:
      - ./:/app/
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    command: sh -c 'go mod tidy && swag init && air'
    depends_on:
      db:
        condition: service_healthy
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/openapi/swagger.yaml
    volumes:
      - ./docs/:/openapi/
    ports:
      - "8081:8080"
    depends_on:
      - go
  db:
    container_name: mysql
    image: mysql:8.4.2
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 30
volumes:
  db-volume: