services:
  go:
    container_name: go-chi
    volumes:
      - ./:/app/
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    command: sh -c 'go mod tidy && swag init && air'
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/openapi/swagger.yaml
    volumes:
      - ./docs/:/openapi/
    ports:
      - "8081:8080"
    depends_on:
      - go
  db:
    container_name: mariadb
    image: mariadb:lts-ubi
    ports:
      - '3306:3306'
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-volume:/var/lib/mysql
volumes:
  db-volume: