services:
  go:
    container_name: go-chi
    volumes:
      - ./:/app/
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    command: sh -c 'go mod tidy && swag init && air'
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/openapi/swagger.yaml
    volumes:
      - ./docs/:/openapi/
    ports:
      - "8081:8080"
    depends_on:
      - go